# 1. Ana Motor Ayarları: NGINX'in arka planda kullanacağı kullanıcı
user www-data;

# 2. Çalışma Kapasitesi: NGINX aynı anda kaç kişiye cevap verecek?
events {
    worker_connections 1024;
}

# 3. HTTP Bloğu (Tüm Web Trafiğinin Kalbi)
http {
    # CSS, JS ve HTML dosyalarının tarayıcıda düzgün görünmesi için şarttır
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Senin Sitenin Özel Ayarları (Server Bloğu)
    server {
        # Sadece ve sadece 443 portunu dinle
        listen 443 ssl;
        listen [::]:443 ssl;

        # Senin kimliğin
        server_name musyilma.42.fr;

        # TLS Sertifikaları (Dockerfile'da ürettiğimiz dijital çelik kasa)
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Güvenlik Protokolleri (Projenin en katı kuralı)
        ssl_protocols TLSv1.2 TLSv1.3;

        # Dosyaların bulunduğu yer ve varsayılan açılış sayfaları
        root /var/www/html;
        index index.php index.html index.htm;

        # Klasik sayfa yönlendirmesi
        location / {
            try_files $uri $uri/ =404;
        }

        # PHP ve WordPress iletişimi için arkadaki 9000 portuna yönlendirme
       location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000; # O BAŞ BELASI YORUMU SİLDİK
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}