server {
        listen 443 ssl; #sadece 443 portundan gelen istekleri dinle ve dümdüz okumal ssl şeklinde gelicek veri
        listen [::]:443 ssl; # ipv6 dan gelen istekleride al

        server_name musyilma.42.fr; # serverimizin ismi olmassa aynı porttan yapılan farklı site yayınlarını bulmak daha zor olur

        ssl_certificate /etc/nginx/ssl/inception.crt; #burada public key varmış bunu sitemizi bağlanan insanların pclerini gönderiyoruz ve burdaki kurallar veya algoritmaya göre verileri şifreleniyor
        ssl_certificate_key /etc/nginx/ssl/inception.key;# private key gibi buda gelen veriyi sadece burdaki algoritma okuyabiliyor. benim aklıma takılan şu eğer public olan versiyonda şifreleniyorsa ordaki algoritmay bakarak şifre çözülemez mi?
        
        ssl_protocols TLSv1.2 TLSv1.3; # gelen isteklere bakıyoruz eğer bizim istediğimiz sürümler değilse içeri almıyoruz

        root /var/www/html; # sitemizin dosyalaraının nerde olduğunu belirtiyoruz bir yerde bişey aranac veya isteneckse buraya gelir.(burası nginxx kanka burdada var/www/html dizini mi var hiç sanmıyrum ne alak şimdi)
        index index.php index.html index.htm; #site ilk açılırken .php uzantılı olduğu için nginxte php bilmediği için biz ne hangi dosyaları okuması gerektiğini gösteriyoruz 1 tanede .html var ama bilmiyorum neden var
        
        location / {  #   biz uzantı gediğinde sonunda .html yoksa buraya girer ve ilk önce dosya sonra klasor olarak aranır en son hiç biir yyoksa 404 döner
            try_files $uri $uri/ =404;
        }

       location ~ \.php$ { # .php uzantılı dosyalarını yine kendimiz yapıyouz nginx bilmediği için
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS on;
        }
}